apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::160618183374:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-YEJM1SFFU7C7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::160618183374:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T07:15:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1919"
  uid: 09f27801-4d88-4a8d-9f0f-140eac42d6f1
